"""Initial schema — all 7 tables

Revision ID: 001
Revises:
Create Date: 2026-04-06

This migration creates every table from scratch. It's the starting point.
All subsequent migrations will build on top of this revision.

We write this migration manually (not autogenerated) so the comments
explaining the design decisions are preserved.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── users ─────────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("daily_digest", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("instant_alerts", sa.Boolean(), nullable=False, server_default="true"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    # ── product_catalog ───────────────────────────────────────────────────────
    op.create_table(
        "product_catalog",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("display_name", sa.String(255), nullable=False),
        sa.Column("vendor", sa.String(255), nullable=False),
        sa.Column("cpe_product", sa.String(255), nullable=False),
        sa.Column("category", sa.String(100), nullable=True),
        sa.Column("icon_url", sa.String(500), nullable=True),
        sa.Column("popular", sa.Boolean(), nullable=False, server_default="false"),
        sa.UniqueConstraint("vendor", "cpe_product", name="uq_catalog_vendor_product"),
    )

    # ── stack_items ───────────────────────────────────────────────────────────
    op.create_table(
        "stack_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("product_name", sa.String(255), nullable=False),
        sa.Column("vendor", sa.String(255), nullable=False),
        sa.Column("cpe_product", sa.String(255), nullable=False),
        sa.Column("version", sa.String(100), nullable=False),
        sa.Column("cpe_string", sa.Text(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "user_id", "cpe_product", "version", name="uq_stack_user_product_version"
        ),
    )
    op.create_index("ix_stack_items_user_id", "stack_items", ["user_id"])
    op.create_index("ix_stack_items_cpe", "stack_items", ["cpe_product", "version"])

    # ── cves ──────────────────────────────────────────────────────────────────
    op.create_table(
        "cves",
        sa.Column("cve_id", sa.String(20), primary_key=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("cvss_vector", sa.String(100), nullable=True),
        sa.Column("epss_score", sa.Float(), nullable=True),
        sa.Column("epss_percentile", sa.Float(), nullable=True),
        sa.Column("kev_flag", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("kev_date_added", sa.Date(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("references", postgresql.JSONB(), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_cves_published_at", "cves", ["published_at"], postgresql_ops={"published_at": "DESC"})
    op.create_index(
        "ix_cves_kev",
        "cves",
        ["kev_flag"],
        postgresql_where=sa.text("kev_flag = true"),
    )

    # ── cve_affected_products ─────────────────────────────────────────────────
    op.create_table(
        "cve_affected_products",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "cve_id",
            sa.String(20),
            sa.ForeignKey("cves.cve_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("vendor", sa.String(255), nullable=False),
        sa.Column("product", sa.String(255), nullable=False),
        sa.Column("cpe_string", sa.Text(), nullable=False),
        sa.Column("version_start", sa.String(100), nullable=True),
        sa.Column("version_start_including", sa.Boolean(), server_default="true"),
        sa.Column("version_end", sa.String(100), nullable=True),
        sa.Column("version_end_including", sa.Boolean(), server_default="false"),
        sa.Column("single_version", sa.String(100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("idx_cve_affected_vendor_product", "cve_affected_products", ["vendor", "product"])
    op.create_index("idx_cve_affected_cve_id", "cve_affected_products", ["cve_id"])

    # ── user_cve_matches ──────────────────────────────────────────────────────
    op.create_table(
        "user_cve_matches",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "cve_id",
            sa.String(20),
            sa.ForeignKey("cves.cve_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "stack_item_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("stack_items.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("priority_score", sa.Float(), nullable=False, server_default="0"),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed", sa.Boolean(), nullable=False, server_default="false"),
        sa.UniqueConstraint("user_id", "cve_id", "stack_item_id", name="uq_match"),
    )
    op.create_index("idx_user_cve_matches_user", "user_cve_matches", ["user_id", "dismissed"])
    op.create_index(
        "idx_user_cve_matches_unseen",
        "user_cve_matches",
        ["user_id", "seen_at"],
        postgresql_where=sa.text("seen_at IS NULL"),
    )

    # ── notifications ─────────────────────────────────────────────────────────
    op.create_table(
        "notifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("notification_type", sa.String(50), nullable=False),
        sa.Column("cve_ids", postgresql.JSONB(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(20), server_default="sent"),
    )
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"])
    op.create_index("ix_notifications_sent_at", "notifications", ["sent_at"])


def downgrade() -> None:
    op.drop_table("notifications")
    op.drop_table("user_cve_matches")
    op.drop_table("cve_affected_products")
    op.drop_table("cves")
    op.drop_table("stack_items")
    op.drop_table("product_catalog")
    op.drop_table("users")
